version: '3.9'

services:
  proxy_server:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "${PORT:-3000}:80"

  static_server_1:
    build:
      context: .
      dockerfile: nodejs.dockerfile
    environment:
      PORT: 9090
      APP_LABEL: "Static server one"

  static_server_2:
    build:
      context: .
      dockerfile: nodejs.dockerfile
    environment:
      PORT: 10050
      APP_LABEL: "Static server two"
